#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const THEME = process.env.THEME || 'tokyo-night-dark';
const themesDir = path.join(__dirname, '../src/themes');
const generatedDir = path.join(__dirname, '../src/generated');
const themePath = path.join(themesDir, `${THEME}.json`);

if (!fs.existsSync(themePath)) {
  console.error(`\x1b[31mError: Theme not found: ${THEME}\x1b[0m`);
  console.error(`Available themes: ${fs.readdirSync(themesDir).filter(f => f.endsWith('.json')).map(f => f.replace('.json', '')).join(', ')}`);
  process.exit(1);
}

const theme = JSON.parse(fs.readFileSync(themePath, 'utf8'));

function hexToRgb(hex) {
  const result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return '0, 0, 0';
  return `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`;
}

function luminance(hex) {
  const [r8, g8, b8] = hexToRgb(hex)
    .split(',')
    .map(v => parseInt(v.trim(), 10) / 255);
  const toLinear = v => (v <= 0.04045 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4));
  return 0.2126 * toLinear(r8) + 0.7152 * toLinear(g8) + 0.0722 * toLinear(b8);
}

// Sort base00/01/02 by luminance to ensure background < surface < surface-elevated
function pickSurfaces() {
  const candidates = [theme.base00, theme.base01, theme.base02].filter(Boolean);
  const sorted = [...candidates].sort((a, b) => luminance(a) - luminance(b));
  return {
    background: sorted[0],
    surface: sorted[1] ?? sorted[0],
    surfaceElevated: sorted[2] ?? sorted[1] ?? sorted[0],
  };
}

const surfaces = pickSurfaces();

// Derive a contrasting foreground for the primary color
function contrastFg(bgHex) {
  return luminance(bgHex) > 0.4 ? surfaces.background : (theme.base07 ?? 'ffffff');
}

const colors = {
  background: surfaces.background,
  surface: surfaces.surface,
  'surface-elevated': surfaces.surfaceElevated,
  border: theme.base03,
  'border-muted': theme.base02,
  text: theme.base06 ?? theme.base05,
  'text-muted': theme.base05 ?? theme.base04,
  'text-subtle': theme.base04 ?? theme.base03,
  primary: theme.base0D,
  'primary-pressed': theme.base0C ?? theme.base0D,
  'on-primary': contrastFg(theme.base0D),
  danger: theme.base08,
  success: theme.base0B,
  warning: theme.base09,
  info: theme.base0C,
  'code-background': surfaces.background,
  'code-text': theme.base05,
  'link': theme.base0D,
  overlay: `rgba(${hexToRgb(surfaces.background)}, 0.6)`,
  'card-shadow': `rgba(${hexToRgb(surfaces.background)}, 0.15)`,
};

// --- Generate CSS using @theme directive (Tailwind v4 / UniWind compatible) ---
const css = `/* Generated from ${theme.name} theme */
/* Do not edit - generated by scripts/build-theme.js */
@theme {
${Object.entries(colors).map(([k, v]) => `  --color-${k}: ${v.startsWith('rgba') ? v : `#${v}`};`).join('\n')}
}
`;

// --- Generate TypeScript colors for useThemeColors hook ---
const tsColors = {};
for (const [k, v] of Object.entries(colors)) {
  // Convert kebab-case to camelCase
  const camel = k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  tsColors[camel] = v.startsWith('rgba') ? v : `#${v}`;
}

const ts = `// Generated from ${theme.name} theme
// Do not edit - generated by scripts/build-theme.js

export const themeColors = ${JSON.stringify(tsColors, null, 2)} as const;

export type ThemeColors = typeof themeColors;
`;

fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(path.join(generatedDir, 'theme.css'), css);
fs.writeFileSync(path.join(generatedDir, 'theme.ts'), ts);
console.log(`\x1b[32m✓ Generated theme: ${theme.name} (${THEME})\x1b[0m`);
console.log(`  CSS: src/generated/theme.css`);
console.log(`  TS:  src/generated/theme.ts`);
