#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const THEME = process.env.THEME || 'tokyo-night-dark';
const themesDir = path.join(__dirname, '../src/themes');
const generatedDir = path.join(__dirname, '../src/generated');
const themePath = path.join(themesDir, `${THEME}.json`);

if (!fs.existsSync(themePath)) {
  console.error(`\x1b[31mError: Theme not found: ${THEME}\x1b[0m`);
  console.error(`Available themes: ${fs.readdirSync(themesDir).filter(f => f.endsWith('.json')).map(f => f.replace('.json', '')).join(', ')}`);
  process.exit(1);
}

const theme = JSON.parse(fs.readFileSync(themePath, 'utf8'));

function hexToRgb(hex) {
  const result = /^([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return '0, 0, 0';
  return `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`;
}

const colors = {
  background: theme.base00,
  surface: theme.base01,
  'surface-elevated': theme.base02,
  border: theme.base03,
  'border-muted': theme.base02,
  text: theme.base05,
  'text-muted': theme.base04,
  'text-subtle': theme.base03,
  primary: theme.base0D,
  'primary-pressed': theme.base0C,
  danger: theme.base08,
  success: theme.base0B,
  warning: theme.base09,
  info: theme.base0C,
  overlay: `rgba(${hexToRgb(theme.base00)}, 0.5)`,
  'card-shadow': `rgba(${hexToRgb(theme.base00)}, 0.3)`,
};

const css = `/* Generated from ${theme.name} theme */
/* Do not edit - generated by scripts/build-theme.js */
:root {
${Object.entries(colors).map(([k, v]) => `  --color-${k}: ${v.startsWith('rgba') ? v : `#${v}`};`).join('\n')}
}
`;

fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(path.join(generatedDir, 'theme.css'), css);
console.log(`\x1b[32m✓ Generated theme: ${theme.name} (${THEME})\x1b[0m`);