name: Build and Test

on:
  workflow_dispatch: {}

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview

  maestro_test:
    needs: [build_android]
    type: maestro
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      flow_path:
        - .maestro/ci-smoke-test.yaml
